version: '3.6'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123@SQLServer
    volumes:
      - /home/mariojunior/csharp/mssql/data:/var/opt/mssql/data
